services:
  anycast-dns:
    build: .
    container_name: anycast-dns-appliance
    network_mode: "host"
    privileged: true
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./adguard-data:/opt/adguardhome/work
      - ./adguard-conf:/opt/adguardhome/conf