log syslog all;
router id ${NODE_IP};

protocol device {
    scan time 10;
}

protocol direct {
    ipv4;
    interface "anycast0";
}

protocol kernel {
    ipv4 { export all; };
}

protocol ospf v2 MyAnycast {
    ipv4 {
        import all;
        export all;
    };
    area 0 {
        interface "${IFACE}" {
            type broadcast;
            hello 1;
            dead 4;
        };
    };
}