[supervisord]
nodaemon=true
user=root

[program:unbound]
command=/usr/sbin/unbound -d -c /etc/unbound/unbound.conf
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autostart=true
autorestart=true
startsecs=5
startretries=3
priority=10

[program:adguard]
command=/usr/bin/adguardhome --config /opt/adguardhome/conf/AdGuardHome.yaml --work-dir /opt/adguardhome/work --no-check-update
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autostart=true
autorestart=true
startsecs=5
startretries=3
priority=20

[program:bird]
command=/usr/sbin/bird -d -c /etc/bird/bird.conf
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autostart=true
autorestart=true
startsecs=5
startretries=3
priority=30

[program:adguard-sync]
command=/usr/bin/adguardhome-sync run --config /opt/adguardhome-sync/config.yaml
environment=ORIGIN_URL="${MASTER_IP}",ORIGIN_USERNAME="${SYNC_USER}",ORIGIN_PASSWORD="${SYNC_PASS}",REPLICA_URL="http://127.0.0.1:80",REPLICA_USERNAME="${SYNC_USER}",REPLICA_PASSWORD="${SYNC_PASS}"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autostart=${SYNC_AUTOSTART}
autorestart=true
startsecs=5
startretries=3
priority=25